on:
  workflow_dispatch:

jobs:
  publish:
    name: Compile and publish ExpansionPanel fork to Maven Central using gradle task
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: launch library publish task
        env:
          SIMLA_MOBILE_APPS_EMAIL: ${{ secrets.SIMLA_MOBILE_APPS_EMAIL }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: ./gradlew :expansionpanel:publishReleasePublicationToMainRepository --stacktrace
